# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/hadmarine/develop/cpp-backend-boilerplate

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/hadmarine/develop/cpp-backend-boilerplate

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hadmarine/develop/cpp-backend-boilerplate/CMakeFiles /Users/hadmarine/develop/cpp-backend-boilerplate/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hadmarine/develop/cpp-backend-boilerplate/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

src/core/rest/REST_Request.o: src/core/rest/REST_Request.cpp.o

.PHONY : src/core/rest/REST_Request.o

# target to build an object file
src/core/rest/REST_Request.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/rest/REST_Request.cpp.o
.PHONY : src/core/rest/REST_Request.cpp.o

src/core/rest/REST_Request.i: src/core/rest/REST_Request.cpp.i

.PHONY : src/core/rest/REST_Request.i

# target to preprocess a source file
src/core/rest/REST_Request.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/rest/REST_Request.cpp.i
.PHONY : src/core/rest/REST_Request.cpp.i

src/core/rest/REST_Request.s: src/core/rest/REST_Request.cpp.s

.PHONY : src/core/rest/REST_Request.s

# target to generate assembly for a file
src/core/rest/REST_Request.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/rest/REST_Request.cpp.s
.PHONY : src/core/rest/REST_Request.cpp.s

src/core/rest/REST_Response.o: src/core/rest/REST_Response.cpp.o

.PHONY : src/core/rest/REST_Response.o

# target to build an object file
src/core/rest/REST_Response.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/rest/REST_Response.cpp.o
.PHONY : src/core/rest/REST_Response.cpp.o

src/core/rest/REST_Response.i: src/core/rest/REST_Response.cpp.i

.PHONY : src/core/rest/REST_Response.i

# target to preprocess a source file
src/core/rest/REST_Response.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/rest/REST_Response.cpp.i
.PHONY : src/core/rest/REST_Response.cpp.i

src/core/rest/REST_Response.s: src/core/rest/REST_Response.cpp.s

.PHONY : src/core/rest/REST_Response.s

# target to generate assembly for a file
src/core/rest/REST_Response.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/rest/REST_Response.cpp.s
.PHONY : src/core/rest/REST_Response.cpp.s

src/core/rest/REST_functions.o: src/core/rest/REST_functions.cpp.o

.PHONY : src/core/rest/REST_functions.o

# target to build an object file
src/core/rest/REST_functions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/rest/REST_functions.cpp.o
.PHONY : src/core/rest/REST_functions.cpp.o

src/core/rest/REST_functions.i: src/core/rest/REST_functions.cpp.i

.PHONY : src/core/rest/REST_functions.i

# target to preprocess a source file
src/core/rest/REST_functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/rest/REST_functions.cpp.i
.PHONY : src/core/rest/REST_functions.cpp.i

src/core/rest/REST_functions.s: src/core/rest/REST_functions.cpp.s

.PHONY : src/core/rest/REST_functions.s

# target to generate assembly for a file
src/core/rest/REST_functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/rest/REST_functions.cpp.s
.PHONY : src/core/rest/REST_functions.cpp.s

src/core/rest/RestDirCollector.o: src/core/rest/RestDirCollector.cpp.o

.PHONY : src/core/rest/RestDirCollector.o

# target to build an object file
src/core/rest/RestDirCollector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/rest/RestDirCollector.cpp.o
.PHONY : src/core/rest/RestDirCollector.cpp.o

src/core/rest/RestDirCollector.i: src/core/rest/RestDirCollector.cpp.i

.PHONY : src/core/rest/RestDirCollector.i

# target to preprocess a source file
src/core/rest/RestDirCollector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/rest/RestDirCollector.cpp.i
.PHONY : src/core/rest/RestDirCollector.cpp.i

src/core/rest/RestDirCollector.s: src/core/rest/RestDirCollector.cpp.s

.PHONY : src/core/rest/RestDirCollector.s

# target to generate assembly for a file
src/core/rest/RestDirCollector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/rest/RestDirCollector.cpp.s
.PHONY : src/core/rest/RestDirCollector.cpp.s

src/core/socket/SocketCollector.o: src/core/socket/SocketCollector.cpp.o

.PHONY : src/core/socket/SocketCollector.o

# target to build an object file
src/core/socket/SocketCollector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/socket/SocketCollector.cpp.o
.PHONY : src/core/socket/SocketCollector.cpp.o

src/core/socket/SocketCollector.i: src/core/socket/SocketCollector.cpp.i

.PHONY : src/core/socket/SocketCollector.i

# target to preprocess a source file
src/core/socket/SocketCollector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/socket/SocketCollector.cpp.i
.PHONY : src/core/socket/SocketCollector.cpp.i

src/core/socket/SocketCollector.s: src/core/socket/SocketCollector.cpp.s

.PHONY : src/core/socket/SocketCollector.s

# target to generate assembly for a file
src/core/socket/SocketCollector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/socket/SocketCollector.cpp.s
.PHONY : src/core/socket/SocketCollector.cpp.s

src/exec/testdir.o: src/exec/testdir.cpp.o

.PHONY : src/exec/testdir.o

# target to build an object file
src/exec/testdir.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/exec/testdir.cpp.o
.PHONY : src/exec/testdir.cpp.o

src/exec/testdir.i: src/exec/testdir.cpp.i

.PHONY : src/exec/testdir.i

# target to preprocess a source file
src/exec/testdir.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/exec/testdir.cpp.i
.PHONY : src/exec/testdir.cpp.i

src/exec/testdir.s: src/exec/testdir.cpp.s

.PHONY : src/exec/testdir.s

# target to generate assembly for a file
src/exec/testdir.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/exec/testdir.cpp.s
.PHONY : src/exec/testdir.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/util/Assets.o: src/util/Assets.cpp.o

.PHONY : src/util/Assets.o

# target to build an object file
src/util/Assets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/util/Assets.cpp.o
.PHONY : src/util/Assets.cpp.o

src/util/Assets.i: src/util/Assets.cpp.i

.PHONY : src/util/Assets.i

# target to preprocess a source file
src/util/Assets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/util/Assets.cpp.i
.PHONY : src/util/Assets.cpp.i

src/util/Assets.s: src/util/Assets.cpp.s

.PHONY : src/util/Assets.s

# target to generate assembly for a file
src/util/Assets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/util/Assets.cpp.s
.PHONY : src/util/Assets.cpp.s

src/util/CLogger.o: src/util/CLogger.cpp.o

.PHONY : src/util/CLogger.o

# target to build an object file
src/util/CLogger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/util/CLogger.cpp.o
.PHONY : src/util/CLogger.cpp.o

src/util/CLogger.i: src/util/CLogger.cpp.i

.PHONY : src/util/CLogger.i

# target to preprocess a source file
src/util/CLogger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/util/CLogger.cpp.i
.PHONY : src/util/CLogger.cpp.i

src/util/CLogger.s: src/util/CLogger.cpp.s

.PHONY : src/util/CLogger.s

# target to generate assembly for a file
src/util/CLogger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/util/CLogger.cpp.s
.PHONY : src/util/CLogger.cpp.s

src/util/Parser.o: src/util/Parser.cpp.o

.PHONY : src/util/Parser.o

# target to build an object file
src/util/Parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/util/Parser.cpp.o
.PHONY : src/util/Parser.cpp.o

src/util/Parser.i: src/util/Parser.cpp.i

.PHONY : src/util/Parser.i

# target to preprocess a source file
src/util/Parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/util/Parser.cpp.i
.PHONY : src/util/Parser.cpp.i

src/util/Parser.s: src/util/Parser.cpp.s

.PHONY : src/util/Parser.s

# target to generate assembly for a file
src/util/Parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/util/Parser.cpp.s
.PHONY : src/util/Parser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... src/core/rest/REST_Request.o"
	@echo "... src/core/rest/REST_Request.i"
	@echo "... src/core/rest/REST_Request.s"
	@echo "... src/core/rest/REST_Response.o"
	@echo "... src/core/rest/REST_Response.i"
	@echo "... src/core/rest/REST_Response.s"
	@echo "... src/core/rest/REST_functions.o"
	@echo "... src/core/rest/REST_functions.i"
	@echo "... src/core/rest/REST_functions.s"
	@echo "... src/core/rest/RestDirCollector.o"
	@echo "... src/core/rest/RestDirCollector.i"
	@echo "... src/core/rest/RestDirCollector.s"
	@echo "... src/core/socket/SocketCollector.o"
	@echo "... src/core/socket/SocketCollector.i"
	@echo "... src/core/socket/SocketCollector.s"
	@echo "... src/exec/testdir.o"
	@echo "... src/exec/testdir.i"
	@echo "... src/exec/testdir.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/util/Assets.o"
	@echo "... src/util/Assets.i"
	@echo "... src/util/Assets.s"
	@echo "... src/util/CLogger.o"
	@echo "... src/util/CLogger.i"
	@echo "... src/util/CLogger.s"
	@echo "... src/util/Parser.o"
	@echo "... src/util/Parser.i"
	@echo "... src/util/Parser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

